# **ARRAY**
### *It is a data structure in the NumPy Library. You can think of it as a List, Dictionary, or Tuple.*

In [1]:
import numpy as np

In [2]:
np.array([2, 4, 6, 8])

array([2, 4, 6, 8])

In [4]:
variable = [5.8, 9, 7, 5]

In [5]:
print(type(variable[0]))
print(type(variable[1]))

<class 'float'>
<class 'int'>


In [6]:
new_variable = np.array([5.8, 9, 7, 5])

In [7]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [8]:
new_variable2 = np.array([5.8, 9, 7, 5], dtype="int")

In [9]:
new_variable2

array([5, 9, 7, 5])